export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  VEHICLES: '/vehicles',
  VEHICLE_DETAILS: (id: string) => `/vehicles/${id}`,
  VEHICLE_NEW: '/vehicles/new',
  VEHICLE_EDIT: (id: string) => `/vehicles/${id}/edit`,
  DRIVERS: '/drivers',
  DRIVER_DETAILS: (id: string) => `/drivers/${id}`,
  DRIVER_NEW: '/drivers/new',
  DRIVER_EDIT: (id: string) => `/drivers/${id}/edit`,
  TRIPS: '/trips',
  TRIP_DETAILS: (id: string) => `/trips/${id}`,
  TRIP_NEW: '/trips/new',
  MAINTENANCE: '/maintenance',
  MAINTENANCE_DETAILS: (id: string) => `/maintenance/${id}`,
  MAINTENANCE_NEW: '/maintenance/new',
  REPORTS: '/reports',
  SETTINGS: '/settings',
} as const;

export const API_ROUTES = {
  VEHICLES: '/api/vehicles',
  VEHICLE: (id: string) => `/api/vehicles/${id}`,
  DRIVERS: '/api/drivers',
  DRIVER: (id: string) => `/api/drivers/${id}`,
  TRIPS: '/api/trips',
  TRIP: (id: string) => `/api/trips/${id}`,
  MAINTENANCE: '/api/maintenance',
  MAINTENANCE_ITEM: (id: string) => `/api/maintenance/${id}`,
  REPORTS: '/api/reports',
  AUTH: {
    LOGIN: '/api/auth/login',
    LOGOUT: '/api/auth/logout',
    REGISTER: '/api/auth/register',
    SESSION: '/api/auth/session',
  },
} as const;
